mysql:
  frota:
    host: mysql-hml
    username: frota
    password: frota
    port: 3306
    database: frota_zn4
  sso:
    host: mysql-hml
    username: frota
    password: frota
    port: 3306
    database: sso

mongodb:
    url: mongodb://mongo-hml:27017/frota_znh

sso:
    url: http://172.18.107.240:3000

rjConsultores:
  url: http://34.198.151.111:9991
  authorization: Basic bTJtOnJqbTJtcmo=

amqp:
    url: amqp://guest:guest@localhost
    servico-persistencia: lazypersistence
    worker-processamento:
      queue: eventos.monitriip
      exchange-dlq: processador.monitriip.DLQ
      routing-key-dql: dead.letters

cache:
  linha:
    seconds: 10
  motorista:
    seconds: 10
  veiculo:
    seconds: 10

server:
  port: 3000

log:
  path: var/log
  maxSize: 100000
  maxFiles: 10
  files:
    erro: monitriip-erro.log
    info: monitriip-info.log



