mysql:
  frota:
    host: 172.16.193.32
    username: frota
    password: frota
    port: 3306
    database: frota_zn4
  sso:
    host: 172.16.193.32 
    username: frota
    password: frota
    port: 3306
    database: sso

mongodb:
    url: mongodb://172.16.193.9:27017/m2mfrota

sso:
    url: http://10.0.1.165:3000

amqp:
    url: amqp://admin:admin@172.16.193.13
    queue: lazypersistence

cache:
  linha:
    seconds: 10
  motorista:
    seconds: 10
  veiculo:
    seconds: 10

server:
  port: 3000

log:
  path: /var/log/monitrip.log