mysql:
  frota:
    host: 10.10.1.104
    username: frota
    password: frota
    port: 3306
    database: frota_zn5
  sso:
    host: 10.10.1.104
    username: frota
    password: frota
    port: 3306
    database: sso

mongodb:
    url: mongodb://10.10.1.16:27017/m2mfrota

sso:
    url: http://sso-poc.m2mfrota.com.br/api

amqp:
    url: amqp://admin:admin@172.16.193.13
    queue: lazypersistence

cache:
  linha:
    seconds: 10
  motorista:
    seconds: 10
  veiculo:
    seconds: 10

server:
  port: 3000